### ISSUE TITLE
hCaptcha support?

### ISSUE THREAD

**Issue by myfirstnameispaul** [bramley/phplist-plugin-recaptcha#1]
Just wondering what would be required for this plugin to support [hCaptcha](https://www.hcaptcha.com/)?

[Using hCaptcha with PHP](https://medium.com/@hCaptcha/using-hcaptcha-with-php-fc31884aa9ea)

**Comment by bramley** [comment]
Their documentation says 
> If you're already using Google's reCAPTCHA, you can use your existing code with a few slight changes

so it might not be too much work. I will try to look into this over the next few days.

**Comment by bramley** [comment]
I have created a new plugin for hCaptcha. It was simpler to do that rather than try to make this plugin support both recaptcha and hcaptcha. 
See https://github.com/bramley/phplist-plugin-hcaptcha
It has similar configuration options as this plugin.

**Comment by myfirstnameispaul** [comment]
Awesome! Thank you!
